baseurl      = "https://mduarteg.github.io/hugo"
title        = "mduarteg"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
publishDir   = "docs"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  homeSubtitle = "A simple and beautiful test"
  disableReadOtherPosts = false
  enableSharingButtons = false

  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello... Friend"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "mduarteg"
      logoHomeLink = "/"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Blog"
    url        = "posts/"
  [[menu.main]]
    identifier = "port"
    name       = "Portfolio"
    url        = "portfolio/"